#!/usr/bin/env python3
"""Turn wire-format-fixture.json into a C header the conformance test includes.

The JSON is the source of truth; this header is a build artifact and is not
committed, so the C test and the web app's vitest test cannot drift apart by
one of them editing a private copy of the data.

Usage: python3 gen_fixture_header.py <fixture.json> <out.h>
"""

import json
import sys


def c_keyframe(kf):
    return (
        "{ .time_ms = %d, .angles = { %d, %d, %d, %d }, "
        ".ease_in_type = %d, .ease_out_type = %d, .ease_in_ms = %d, .ease_out_ms = %d }"
    ) % (
        kf["timeMs"],
        kf["angles"][0],
        kf["angles"][1],
        kf["angles"][2],
        kf["angles"][3],
        kf["easeInType"],
        kf["easeOutType"],
        kf["easeInMs"],
        kf["easeOutMs"],
    )


def c_bytes(hex_lines):
    raw = "".join(hex_lines)
    if len(raw) % 2 != 0:
        raise SystemExit("fixture hex has an odd number of digits")
    octets = ["0x%s" % raw[i : i + 2] for i in range(0, len(raw), 2)]
    lines = [
        "        " + ", ".join(octets[i : i + 12]) for i in range(0, len(octets), 12)
    ]
    return ",\n".join(lines)


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_fixture_header.py <fixture.json> <out.h>")

    with open(sys.argv[1]) as handle:
        fixture = json.load(handle)

    if fixture["channels"] != 4:
        raise SystemExit("firmware keyframes are 4-channel; fixture declares %d" % fixture["channels"])

    out = [
        "/* Generated by test/gen_fixture_header.py. Do not edit, do not commit. */",
        "#ifndef WIRE_FORMAT_FIXTURE_H",
        "#define WIRE_FORMAT_FIXTURE_H",
        "",
        '#include "custom_animation_types.h"',
        "",
        "typedef struct {",
        "    const char *name;",
        "    custom_animation_t anim;",
        "    uint16_t byte_len;",
        "    uint8_t bytes[CUSTOM_ANIMATION_MAX_SERIALIZED_SIZE];",
        "} fixture_case_t;",
        "",
        "static const fixture_case_t FIXTURE_CASES[] = {",
    ]

    for case in fixture["cases"]:
        keyframes = case["payload"]["keyframes"]
        byte_len = len("".join(case["hex"])) // 2
        out += [
            "    {",
            '        .name = "%s",' % case["name"],
            "        .anim = {",
            "            .keyframe_count = %d," % len(keyframes),
            "            .keyframes = {",
        ]
        out += ["                %s," % c_keyframe(kf) for kf in keyframes]
        out += [
            "            },",
            "        },",
            "        .byte_len = %d," % byte_len,
            "        .bytes = {",
            c_bytes(case["hex"]),
            "        },",
            "    },",
        ]

    out += [
        "};",
        "",
        "#define FIXTURE_CASE_COUNT (sizeof(FIXTURE_CASES) / sizeof(FIXTURE_CASES[0]))",
        "",
        "#endif /* WIRE_FORMAT_FIXTURE_H */",
        "",
    ]

    with open(sys.argv[2], "w") as handle:
        handle.write("\n".join(out))


if __name__ == "__main__":
    main()
