#!/usr/bin/env python3
"""Compute device serials with hashlib.

An independent implementation of docs/ble-protocol.md S8.1, written from the
spec rather than from main/device_serial.c, so agreement between the two means
the derivation is right and not merely self-consistent.

Usage:
    python3 gen_serial_vectors.py <out.h>       vectors as a C header the test
                                                includes; a build artifact, not
                                                committed
    python3 gen_serial_vectors.py --mac <mac>   the serial for one MAC, to check
                                                a real unit at the bench against
                                                something other than its own
                                                firmware
"""

import hashlib
import sys

DOMAIN = b"milklab-ears-serial-v1"
SERIAL_BYTES = 6
MAC_BYTES = 6

# Enough MACs to pin the derivation: a real Espressif OUI, both extremes of the
# input range, and two that differ in one bit at either end of the MAC.
MACS = {
    "espressif_oui": "84fce6001122",
    "all_zero_mac": "000000000000",
    "all_ones_mac": "ffffffffffff",
    "low_bit_set": "000000000001",
    "high_bit_set": "800000000000",
}


def derive(mac):
    if len(mac) != MAC_BYTES:
        raise SystemExit("a MAC is %d bytes, got %d" % (MAC_BYTES, len(mac)))
    return hashlib.sha256(DOMAIN + mac).digest()[:SERIAL_BYTES]


def c_bytes(raw):
    return ", ".join("0x%02x" % byte for byte in raw)


def main():
    if len(sys.argv) == 3 and sys.argv[1] == "--mac":
        mac = bytes.fromhex(sys.argv[2].replace(":", "").replace("-", ""))
        print(derive(mac).hex())
        return

    if len(sys.argv) != 2:
        raise SystemExit(__doc__)

    out = [
        "/* Generated by test/gen_serial_vectors.py. Do not edit, do not commit. */",
        "#ifndef DEVICE_SERIAL_VECTORS_H",
        "#define DEVICE_SERIAL_VECTORS_H",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint8_t mac[%d];" % MAC_BYTES,
        "    uint8_t serial[%d];" % SERIAL_BYTES,
        "} serial_vector_t;",
        "",
        "static const serial_vector_t SERIAL_VECTORS[] = {",
    ]

    for name, mac_hex in MACS.items():
        mac = bytes.fromhex(mac_hex)
        serial = derive(mac)
        out += [
            "    {",
            '        .name = "%s",' % name,
            "        .mac = { %s }," % c_bytes(mac),
            "        .serial = { %s }," % c_bytes(serial),
            "    },",
        ]

    out += [
        "};",
        "",
        "#define SERIAL_VECTOR_COUNT (sizeof(SERIAL_VECTORS) / sizeof(SERIAL_VECTORS[0]))",
        "",
        "#endif /* DEVICE_SERIAL_VECTORS_H */",
        "",
    ]

    with open(sys.argv[1], "w") as handle:
        handle.write("\n".join(out))


if __name__ == "__main__":
    main()
